Fix docs
yiisoft/hydrator-validator pull request #27
Opened 2024-08-10 17:36 UTC by arogachev

| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ❌
| Breaks BC?    | ❌

2024-08-11 08:57 UTC, vjik requested changes

2024-08-11 08:57 UTC, vjik commented on README.md
> +- it allows to validate raw data of properties marked with `Validate` PHP attribute before passing it to the decorated
It's not true. Raw data validation occurs during attributes processing in decorated hydrator. That is, raw data passed to decaorated hydrator without validation.

2024-08-15 18:07 UTC, samdark approved these changes

2024-08-15 18:07 UTC, samdark commented on README.md
> +- it allows to validate object after creating or populating it.
```suggestion
Validating hydrator is a decorator for [hydrator](https://github.com/yiisoft/hydrator) that allows to validate:

- raw data of properties marked with `Validate` PHP attribute;
- an object after creating or populating it.
```

2024-08-20 07:34 UTC, merged